version: '3.1'

services:

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: test

    ports:
      - 5445:5432
    volumes:
      - ./sql:/sql
  pgdb-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: test

    ports:
      - 5446:5432
