version: '3.1'

services:

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_USER: test

    ports:
      - 5445:5432
    volumes:
      - ./sql:/sql

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24